apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ROLE_ARN}}

# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: load-balancer-service-token
#   namespace: kube-system
#   annotations:
#     kubernetes.io/service-account.name: load-balancer-service-account
# type: kubernetes.io/service-account-token