apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-balancer-service-account
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ROLE_ARN}}

---
apiVersion: v1
kind: Secret
metadata:
  name: load-balancer-service-token
  annotations:
    kubernetes.io/service-account.name: load-balancer-service-account
type: kubernetes.io/service-account-token