---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-service-sa
  namespace: micro-service
  annotations:
    eks.amazonaws.com/role-arn: {{S3_BUCKET_ACCESS_ROLE_ARN}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micro-service-pvc
  namespace: micro-service
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-deployment
  namespace: micro-service
  labels:
    app: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-service
  template:
    metadata:
      labels:
        app: micro-service
    spec:
      serviceAccountName: micro-service-sa
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: micro-service-pvc
      containers:
      - name: micro-service
        image: amazon/aws-cli
        command: ['sleep', '10000']
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/hello-data"
            name: storage
