---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-service-sa
  namespace: micro-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::141643165132:role/eu-central-1-eks-application-cluster-S3BucketAccessRole

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-service-deployment
  namespace: micro-service
  labels:
    app: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-service
  template:
    metadata:
      labels:
        app: micro-service
    spec:
      serviceAccountName: micro-service-sa
      containers:
      - name: micro-service
        image: amazon/aws-cli
        command: ['sleep', '10000']
        ports:
        - containerPort: 8080
