Parameters:
  DefaultSecurityGroup:
    Type: String
    Description: Default Security Group
  PublicSubnetId:
    Type: String
    Description: Public Subnet
  PrivateSubnetId:
    Type: String
    Description: Private Subnet
  VpcId:
    Type: String
    Description: VpcId

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Role4EC2WebServer
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ListEksClustersPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - eks:ListClusters
                Resource: "*"

  EC2InstanceProfile:
    DependsOn: EC2Role
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref EC2Role

  MyEC2InstancePublic:
    DependsOn: EC2InstanceProfile
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      KeyName: my-application-key
      ImageId: ami-0dac2efb38d54a859
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref DefaultSecurityGroup
          SubnetId: !Ref PublicSubnetId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          sudo systemctl start httpd

  MyEC2InstancePrivate:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      KeyName: my-application-key
      ImageId: ami-0dac2efb38d54a859
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeviceIndex: 0
          GroupSet:
            - !Ref DefaultSecurityGroup
          SubnetId: !Ref PrivateSubnetId

  MyTargetGroup:
    DependsOn: MyEC2InstancePublic
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "MyTargetGroup"
      Port: 80
      Protocol: HTTP
      # Targets:
      #     Id: !GetAtt MyEC2InstancePublic.InstanceId
      #     Port: 80
      VpcId: !Ref VpcId
