Parameters:
  S3BucketName:
    Type: String
    Description: "Cloud Foramation S3 Bucket"
    Default: bucket-with-stacks
  VpcName:
    Type: String
    Description: "VPC Name"
  ClusterName:
    Type: String
    Description: AWS EKS Cluster Name
  CreateNetworkStack:
    Type: String
    Default: false
    Description: It determines if Network stack should be created
    AllowedValues: [true, false]
  CreateEC2Stack:
    Type: String
    Default: false
    Description: It determines if EC2 stack should be created
    AllowedValues: [true, false]
  CreateEKSStack:
    Type: String
    Default: false
    Description: It determines if EKS stack should be created
    AllowedValues: [true, false]

Conditions:
  IsNetworkStackNeeded: !Equals
    - !Ref CreateNetworkStack
    - true
  IsEC2StackNeeded: !Equals
    - !Ref CreateEC2Stack
    - true
  IsEKSStackNeeded: !Equals
    - !Ref CreateEKSStack
    - true

Resources:

  NetworkStack:
    Condition: IsNetworkStackNeeded
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcName: !Ref VpcName
      TimeoutInMinutes: 10
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/network-template.yml"]]

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Condition: IsEC2StackNeeded
    Properties:
      Parameters:
        PublicSubnetId: !GetAtt NetworkStack.Outputs.PublicSubnetA
        PrivateSubnetId: !GetAtt NetworkStack.Outputs.PrivateSubnetX
        DefaultSecurityGroup: !GetAtt NetworkStack.Outputs.DefaultSecurityGroup
      TimeoutInMinutes: 10
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/ec2-template.yml"]] 

  EKSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Condition: IsEKSStackNeeded  
    Properties:
      Parameters:
        ClusterName: !Ref ClusterName
        DefaultSecurityGroup: !GetAtt NetworkStack.Outputs.DefaultSecurityGroup
        PublicSubnetA: !GetAtt NetworkStack.Outputs.PublicSubnetA
        PublicSubnetB: !GetAtt NetworkStack.Outputs.PublicSubnetB
        PublicSubnetC: !GetAtt NetworkStack.Outputs.PublicSubnetC
        PrivateSubnetX: !GetAtt NetworkStack.Outputs.PrivateSubnetX
        PrivateSubnetY: !GetAtt NetworkStack.Outputs.PrivateSubnetY
        PrivateSubnetZ: !GetAtt NetworkStack.Outputs.PrivateSubnetZ
      TimeoutInMinutes: 10
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/eks.yml"]] 

Outputs:
  ApplicationEksClusterVpc:
    Description: VPC
    Value: !GetAtt NetworkStack.Outputs.ClusterVPC
    Export:
      Name: ApplicationEksClusterVpc
  LoadBalancerControllerRoleArn:
    Condition: IsEKSStackNeeded
    Description: AwsLoadBalancerControllerRole
    Value: !GetAtt EKSStack.Outputs.LoadBalancerControllerRole
    Export:
      Name: LoadBalancerControllerRoleArn
