Parameters:
  StackName:
    Type: String
    Description: "Main Stack Name"
  S3BucketName:
    Type: String
    Description: "Cloud Foramation S3 Bucket"
    Default: bucket-with-stacks
  VpcName:
    Type: String
    Description: "VPC Name"
  ClusterName:
    Type: String
    Description: AWS EKS Cluster Name
  CreateNetworkStack:
    Type: String
    Default: false
    Description: It determines if Network stack should be created
    AllowedValues: [true, false]
  CreateEC2Stack:
    Type: String
    Default: false
    Description: It determines if EC2 stack should be created
    AllowedValues: [true, false]
  CreateEKSStack:
    Type: String
    Default: false
    Description: It determines if EKS stack should be created
    AllowedValues: [true, false]

Conditions:
  IsNetworkStackNeeded: !Equals
    - !Ref CreateNetworkStack
    - true
  IsEC2StackNeeded: !Equals
    - !Ref CreateEC2Stack
    - true
  IsEKSStackNeeded: !Equals
    - !Ref CreateEKSStack
    - true

Resources:

  NetworkStack:
    Condition: IsNetworkStackNeeded
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcName: !Ref VpcName
      TimeoutInMinutes: 10
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/network-template.yml"]]

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Condition: IsEC2StackNeeded
    Properties:
      Parameters:
        StackName: !Ref StackName
        VpcId: !GetAtt NetworkStack.Outputs.ClusterVPC
        PublicSubnetIdA: !GetAtt NetworkStack.Outputs.PublicSubnetA
        PublicSubnetIdB: !GetAtt NetworkStack.Outputs.PublicSubnetB
        PrivateSubnetId: !GetAtt NetworkStack.Outputs.PrivateSubnetX
        DefaultSecurityGroup: !GetAtt NetworkStack.Outputs.DefaultSecurityGroup
      TimeoutInMinutes: 20
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/ec2-template.yml"]] 

  EKSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Condition: IsEKSStackNeeded  
    Properties:
      Parameters:
        StackName: !Ref StackName
        ClusterName: !Ref ClusterName
        DefaultSecurityGroup: !GetAtt NetworkStack.Outputs.DefaultSecurityGroup
        PublicSubnetA: !GetAtt NetworkStack.Outputs.PublicSubnetA
        PublicSubnetB: !GetAtt NetworkStack.Outputs.PublicSubnetB
        PublicSubnetC: !GetAtt NetworkStack.Outputs.PublicSubnetC
        PrivateSubnetX: !GetAtt NetworkStack.Outputs.PrivateSubnetX
        PrivateSubnetY: !GetAtt NetworkStack.Outputs.PrivateSubnetY
        PrivateSubnetZ: !GetAtt NetworkStack.Outputs.PrivateSubnetZ
      TimeoutInMinutes: 20
      TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/eks.yml"]] 

  # WebServiceDependencies:
  #   Type: AWS::CloudFormation::Stack
  #   Condition: IsEKSStackNeeded 
  #   DependsOn: EKSStack
  #   Properties:
  #     Parameters:
  #       EKSClusterEndpoint: !GetAtt EKSStack.Outputs.EKSClusterEndpoint
  #       StackName: !Ref StackName
  #     TemplateURL: !Join ["", ["https://", !Ref S3BucketName, ".s3.", !Ref "AWS::Region", ".amazonaws.com/web-service-dependencies.yml"]]

  S3BucketAccessRole:
      Type: AWS::IAM::Role
      DependsOn: EKSStack
      Properties:
        RoleName: !Join [ '-', [ !Ref "AWS::Region", !Ref StackName, "S3BucketAccessRole"] ]
        AssumeRolePolicyDocument: !Sub
          - |
                    {
                      "Version": "2012-10-17",
                      "Statement": [
                        {
                          "Effect": "Allow",
                          "Principal": {
                            "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${Id}"
                          },
                          "Action": "sts:AssumeRoleWithWebIdentity",
                          "Condition": {
                            "StringEquals": {
                              "oidc.eks.${AWS::Region}.amazonaws.com/id/${Id}:sub": "system:serviceaccount:${Namespace}:${ServiceAccount}"                            }
                          }
                        }
                      ]
                    }
          - Id:
                      !Select [
                          0,
                          !Split [
                              ".",
                              !Select [
                                  1,
                                  !Split ["://", !GetAtt EKSStack.Outputs.EKSClusterEndpoint],
                              ],
                          ],
                      ]
            Namespace: micro-service-sa
            ServiceAccount: micro-service

  S3BucketAccessPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - S3BucketAccessRole
    Properties:
      Roles:
        - S3BucketAccessRole
      PolicyName: !Join [ '-', [ !Ref "AWS::Region", !Ref StackName, "S3BucketAccessPolicy"] ]
      PolicyDocument: |
        {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "VisualEditor0",
                "Effect": "Allow",
                "Action": [
                    "s3:ListAccessPointsForObjectLambda",
                    "s3:GetAccessPoint",
                    "s3:PutAccountPublicAccessBlock",
                    "s3:ListAccessPoints",
                    "s3:CreateStorageLensGroup",
                    "s3:ListJobs",
                    "s3:PutStorageLensConfiguration",
                    "s3:ListMultiRegionAccessPoints",
                    "s3:ListStorageLensGroups",
                    "s3:ListStorageLensConfigurations",
                    "s3:GetAccountPublicAccessBlock",
                    "s3:ListAllMyBuckets",
                    "s3:ListAccessGrantsInstances",
                    "s3:PutAccessPointPublicAccessBlock",
                    "s3:CreateJob"
                ],
                "Resource": "*"
            },
            {
                "Sid": "VisualEditor1",
                "Effect": "Allow",
                "Action": "s3:*",
                "Resource": "arn:aws:s3:::bucket-with-stacks"
            }
          ]
        }

Outputs:
  ApplicationEksClusterVpc:
    Condition: IsNetworkStackNeeded
    Description: VPC
    Value: !GetAtt NetworkStack.Outputs.ClusterVPC
    Export:
      Name: ApplicationEksClusterVpc
  LoadBalancerControllerRoleArn:
    Condition: IsEKSStackNeeded
    Description: AwsLoadBalancerControllerRole
    Value: !GetAtt EKSStack.Outputs.LoadBalancerControllerRole
    Export:
      Name: LoadBalancerControllerRoleArn
